name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        run: |
          mkdir -p .vercel
          echo '{ "orgId": "'$VERCEL_ORG_ID'", "projectId": "'$VERCEL_PROJECT_ID'" }' > .vercel/project.json
          vercel --prod --token=$VERCEL_TOKEN --confirm --scope=$VERCEL_ORG_ID
